#!/bin/sh

[ "Z$ACTION" = "Zifup" -a "Z$INTERFACE" = "Zwan" ] || exit 0

sleep 10 && /etc/init.d/turboacc restart
logger -t turboacc "Reloading turboacc due to $ACTION of $INTERFACE ($DEVICE)"

exit 0
